print("Hello,World!")
print("Laiba")
print("Laiba Nadeem")
print("1,2,3")
print("Hello\nWorld")
print("Hello\tWorld")
print("apple","banana","cherry",sep=",")
print(1,2,3,sep="-")
print("Hello","World")
print(1,2,3,sep="")
print('He said,"Hello!".')
print("This a backslash:\\")
print("I am 20 years old")
print("This is number 5")
print(1)
print(2)
print(3)
print(4)
print(5)

